name: 🐛 Bug Report
description: Report a bug or unexpected behavior in hl
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the information below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Run command '...'
        2. With input file '...'
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: |
        Please provide details about your environment.
      placeholder: |
        - hl version: (output of `hl --version`)
        - OS: (e.g., Ubuntu 22.04, macOS 14, Windows 11)
        - Terminal: (e.g., iTerm2, Windows Terminal, Alacritty)
        - Shell: (e.g., bash, zsh, fish)
      value: |
        - hl version: 
        - OS: 
        - Terminal: 
        - Shell: 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      description: If applicable, add logs or error messages.
      placeholder: Paste logs or error messages here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, sample log files, configuration files, etc.).
