name: ✨ Feature Request
description: Suggest a new feature or enhancement for hl
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Before submitting, please search existing feature requests and discussions to avoid duplicates.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation and Use Case
      description: |
        Why do you need this feature? What problem does it solve?
        Describe your use case and how this feature would help you.
      placeholder: |
        I'm working with logs that...
        This feature would help me...
    validations:
      required: true

  - type: textarea
    id: example-usage
    attributes:
      label: Example Usage
      description: |
        Show how you would use this feature. Include command examples, configuration snippets, or expected output.
      placeholder: |
        # Example command
        hl --new-feature input.log
        
        # Example output
        ...
      render: shell

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: |
        Have you considered any alternative solutions or workarounds?
        Are there similar features in other tools?

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
