#:schema https://raw.githubusercontent.com/pamburus/hl/v0.36.1/schema/json/config.schema.json

# Preset for OpenTelemetry logs serialized as flat JSON (OTLP JSON).
# See https://opentelemetry.io/docs/specs/otel/logs/data-model/

# Settings for fields processing.
[fields]
ignore = ["_*"]
hide = []

# Configuration of the predefined set of fields.
[fields.predefined]
time.names = ["Timestamp", "ObservedTimestamp"]
logger.names = ["InstrumentationScope.Name"]
message.names = ["Body"]
caller.names = ["code.function"]
caller-file.names = ["code.filepath"]
caller-line.names = ["code.lineno"]

# OpenTelemetry severity text.
# See https://opentelemetry.io/docs/specs/otel/logs/data-model/#field-severitytext
[[fields.predefined.level.variants]]
names = ["SeverityText"]

[fields.predefined.level.variants.values]
trace = ["trace", "trace2", "trace3", "trace4"]
debug = ["debug", "debug2", "debug3", "debug4"]
info = ["info", "info2", "info3", "info4"]
warning = ["warn", "warn2", "warn3", "warn4"]
error = [
  "error", "error2", "error3", "error4",
  "fatal", "fatal2", "fatal3", "fatal4"
]

# OpenTelemetry severity number.
# See https://opentelemetry.io/docs/specs/otel/logs/data-model/#field-severitynumber
[[fields.predefined.level.variants]]
names = ["SeverityNumber"]

[fields.predefined.level.variants.values]
trace = [1, 2, 3, 4]
debug = [5, 6, 7, 8]
info = [9, 10, 11, 12]
warning = [13, 14, 15, 16]
error = [17, 18, 19, 20, 21, 22, 23, 24]
