[package]
name = "heapopt"
version = "0.1.1"
edition.workspace = true
description = "Optimized collections for minimal heap usage"
repository.workspace = true
license.workspace = true

[dependencies]
derive-where.workspace = true
heapless.workspace = true

[dev-dependencies]
more-asserts.workspace = true
